from ArbolAvl import ArbolAvl
from activo import activo
from Cmd import cmd
avl= ArbolAvl()
prueba1=activo("mesa", "mesagrande", "a51")
prueba2=activo("silla", "silla" ,"b42")
prueba3=activo("telefono", "cellular", "a17")
prueba4=activo("cuaderno", "cua", "s60")
prueba5=activo("desodo", "desodo", "a48")
prueba6=activo("lampara", "lampara", "a98")
prueba7=activo("carpa","carpa", "a90")
prueba8=activo("adorno", "adorno", "a7")
prueba9=activo("lapic", "b12", "A9")
prueba10=activo("lana", "lana", "z10")
prueba11=activo("lana", "lana", "z11")
prueba12=activo("lana", "lana", "g10")

avl.insertar(prueba1)
avl.insertar(prueba2)
avl.insertar(prueba3)
avl.insertar(prueba4)
avl.insertar(prueba5)
avl.insertar(prueba6)
avl.insertar(prueba7)
avl.insertar(prueba8)
avl.insertar(prueba9)
avl.insertar(prueba10)
avl.insertar(prueba11)
avl.insertar(prueba12)
parametro=avl.recorrer()
cmd=cmd()
cmd.escribir_dot(parametro, "imagen_Avl")
cmd.ejecutar_cmd("imagen_Avl")
