from ArbolAvl import ArbolAvl
from Entero import Entero
from Cmd import cmd
avl= ArbolAvl()
prueba1=Entero(51)
prueba2=Entero(31)
prueba3=Entero(17)
prueba4=Entero(60)
prueba5=Entero(48)
prueba6=Entero(98)
prueba7=Entero(90)
prueba8=Entero(7)
prueba9=Entero(9)
prueba10=Entero(10)

avl.insertar(prueba1)
avl.insertar(prueba2)
avl.insertar(prueba3)
avl.insertar(prueba4)
avl.insertar(prueba5)
avl.insertar(prueba6)
avl.insertar(prueba7)
avl.insertar(prueba8)
avl.insertar(prueba9)
avl.insertar(prueba10)
parametro=avl.recorrer()
cmd=cmd()
cmd.escribir_dot(parametro, "imagen_Avl")
cmd.ejecutar_cmd("imagen_Avl")
